on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:    
      fail-fast: false
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker hub
        uses: docker/build-push-action@v1
        with:
          file: docker/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          add_git_labels: true
          repository: ${{ github.repository }}
          tags: latest
